const express = require('express');
const app = express();
const port = 3000;

const swaggerJsdoc= require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');
const cors = require('cors');

const { body, validationResult } = require('express-validator');

const options = {
    swaggerDefinition: {
        Info: {
            title: 'Database API',
            version: '1.0.0',
            description: 'Database API autogenerated by swagger docs ',

        },
        host: 'localhost:3000',
        basepath: '/'
    },
    apis: ['./server.js'],
};

const specs= swaggerJsdoc(options);

app.use('/docs', swaggerUi.serve,swaggerUi.setup(specs));
app.use(cors());

const mariadb = require('mariadb');
const pool = mariadb.createPool({
      host: 'localhost',
      user:'root',
      password: 'root',
      database: 'sample',
      port: 3306,
      connectionLimit: 5
});


/**
 * @swagger
 * /:
 *    get:
 *      description: Return Hello
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: Display Hello
 */

app.get('/', (req,res)=> {
res.send('Hello');

});

/**
 * @swagger
 * /api/v1/agents/0.15:
 *    get:
 *      description: Return Agent_code, Agent_name, country of the agent where commission is 0.15
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: object agents details from the database are displayed
 */

 app.get('/api/v1/agents/0.15', async(req,res) => {
    try{
        var result = await pool.query("select AGENT_CODE, AGENT_NAME, COUNTRY from agents where COMMISSION=0.15")
         res.setHeader('Content-Type','Application/json');
         res.statusCode=200;
         res.json(result);
         }
     catch(err){
         throw err;
         }
 });
 
 /**
  * @swagger
  * /api/v1/customers:
  *    get:
  *      description: Return customers code, Name, Grade of the customers where grade is 1
  *      produces:
  *          - application/json
  *      responses:
  *          200:
  *              description: object Customer details from the database are displayed
  */
 
 
 app.get('/api/v1/customers', async(req,res) => {
  try{
       var result = await pool.query('select CUST_CODE ,CUST_NAME ,GRADE from customer where GRADE= 1')
       res.statusCode = 200;
       res.setHeader('Content-Type','Application/json');
       res.json(result);
       //res.send(result);
 }
    catch(err){
        throw err;
        }
 
 });

 
/**
 * @swagger
 * /api/v1/company/19:
 *    get:
 *      description: Return all company details where company id is 19
 *      produces:
 *          - application/json
 *      responses:
 *          200:
 *              description: object company containing all details are displayed
 */

app.get('/api/v1/company/19', async(req,res) =>{
    try{
      var result = await pool.query('select * from company where COMPANY_ID = 19')
      //res.send(result);
      res.statusCode = 200;
      res.setHeader('Content-Type','Application/json');
      res.json(result);
     }
    catch(err){
        throw err;
        }
});




app.listen(port,() => {
console.log('Example app Listening at http://localhost:', port)

});


 